###obteniendo los datos
GET http://127.0.0.1:4000/products

###obteniendo un producto
GET http://127.0.0.1:4000/products/laptop

###añadiendo producto
POST http://127.0.0.1:4000/products
Content-Type: application/json

{
    "name": "laptop",
    "price": 800,
    "quantity": 4
}
###actualizando producto
PUT http://127.0.0.1:4000/products/laptop
Content-Type: application/json

{
    "name": "laptop",
    "price": 75,
    "quantity": 1
}

###eliminar producto
DELETE http://127.0.0.1:4000/products/laptop
